# https://docs.travis-ci.com/user/languages/android/
language: android
jdk: openjdk8
sudo: false

android:
  components:
      - tools
      - platform-tools
      - tools

      - build-tools-28.0.3
      - android-28

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.m2